apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:K8DxNKXzg+FIKsOam32fnz25x6TK,iv:hRcBZe8bfpwzK4CRJ7rTubrne8UsJL/+6dcfON+NSQ8=,tag:3oU61uBOoLpYkTDoCefznQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:wthUZcbZO1w6CKUUTbtLsuiT+5rT0u4S+f3XUqpiI/V9N5YZTA==,iv:/woCu3IsgaLdoTN8lVRaGHWe0uKp2+Ka7lcnkh+DWX8=,tag:h4pq8ys2atxVzJZz+YtyPw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:cRrxMnW6e2wMnIgKsCeK4XGQ,iv:/vb/dUicRqOywjbjWWIGq4wZVknFYMsX6pEsSPNfDu8=,tag:syZ8jl24uYgTsuraDGQc+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk26k3ewlz9n0fs5thrpzaq2mfrkp8tx66cnlmp8jmuaqgjzksvq00h75v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTGUxbXZrTllYa1JCejQy
            cHM2S2xBeGdtN0VMNDBEK29EalVaSFB1NFVNCjhtcGVhdlJsbkRCUG4rV1pYNE1Y
            bDUwTFNCazRCYmx1TEkzU2dPdTJrdzgKLS0tIGhBQ3AvWXNMQ0xXVThBVmgzQmVw
            Rzdxc2JjcEdFWGEvSkpWNmVSNXRZSEUKRwbXf5opLlVpdiqEMD+702YbPFP0QwN2
            pfCUOnipRO48cwMyrzs9P45LfqvQKIjMhyzucie679dNmTwD81Vofg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-13T01:31:39Z"
    mac: ENC[AES256_GCM,data:26Ky6Tz+un5eHXod0OkuA8leDKf77sIcfU7hBIHKF+haBWMJ8z0TIgrR3v0N9JTB7YkRkh8+vuUyYk7U9vnLHDk0gCe5t+LWqNCY/iqNLCNiZb4eR2FPaSW5SbaXd72VdVl5oZmxBxKYO3tEsdg5AS4pdFZfymh4Xca11BCrlGc=,iv:etCpT7pJ02oOKkiTbSImdlMY4PfrQ18YJI67oy7SXy4=,tag:PcX9smYhaE95KArr2STMxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
