---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 15m
  chart:
    spec:
      chart: rancher
      version: 2.7.2
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hostname: rancher.red-panda.xyz
    ingress:
      extraAnnotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: |
          10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hajimari.io/icon: mdi:account-cowboy-hat
    replicas: 1
    global:
      cattle:
        psp:
          enabled: false
  valuesFrom:
    - kind: Secret
      name: rancher-credentials
      valuesKey: adminPassword
      targetPath: bootstrapPassword
