apiVersion: v1
kind: Secret
metadata:
    name: smbcreds
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:fI7p,iv:M/dVW71DPhXEkhIVSLrEN5BCzQJ4Jfsw5IH34zLPtlY=,tag:TNv0I17vUaqsBE+Jx8AB2A==,type:str]
    password: ENC[AES256_GCM,data:VC+4tDGh6S2ZszLSEk4=,iv:Uj2t69G0pal4o72ioTyzc7Gs2Rnkin9b4pNh/O+Ip3o=,tag:GAkG9+YPNzb4zff8SGpHqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk26k3ewlz9n0fs5thrpzaq2mfrkp8tx66cnlmp8jmuaqgjzksvq00h75v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UW1YZ0lkWngzZ0pkK0Fr
            UWUvUVBaU3B6ZnlLWTN2NzNjM2Z2NE0vMEdrCmV0dC9tV2V0a0lMZlNJNFZZLzVh
            V3JWdFczMFEzV2gweHpTQUNaR3VPY1kKLS0tIGk5cnZ2Y1RrRFl3cUZ3d1c3VXlz
            ZWtNb3ZWNzNQT3hLSHRuTysramMzTzgK57pxx6INLCLIn3i6nfPcTRycANY0mu+y
            RzTGh8fiOPSBAmnAMxhvqcZqE5RTinrlidZf1HdBDlGAU71nuyZihQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-04T21:51:16Z"
    mac: ENC[AES256_GCM,data:zsqoUA33y8M4/Chk0kzs2cikKSl1PLkqpsh5K3sohkU/Y1nEHgp4rZ8miqufXQga6P45IOhc4Egu1Cb6kxEUyi+SpA4XpwS+Td8webxOB5JeJeIKpRarn3emzl7AafjRMj1mYm4b1VV5gd2bK8XQAOnwyzoU5J13f4Bun/q3Ja0=,iv:zSXhqR1lKfH4jdedE0rTfgbu5V43DM4sm0aXCqifThE=,tag:VpJMoPDLP237YGLvwMIEjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
