kind: ENC[AES256_GCM,data:UQ8LFynR,iv:9Mxn8UfHZemZB2Jc5fW3fzG0146+mfXwGY99CmBb844=,tag:hNvJFGpgAVD79VN2hMm+CA==,type:str]
ansible_user: ENC[AES256_GCM,data:UwbIBUkLjA==,iv:YhRSOI08+FxLUyDvKr313amiozwlikxzM6/XSdwXI7I=,tag:uOIdzN6c+vPPOdcc0ULimw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:LXFSQ2Vb1oRIfva3FKn4Enxb6NE=,iv:qtSpu2jhA9Ptu5TdGoGoR17kFrIie2JUYDY6gHGRbDA=,tag:a/OubRrXSdIhcW8XbWx6SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk26k3ewlz9n0fs5thrpzaq2mfrkp8tx66cnlmp8jmuaqgjzksvq00h75v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUmxuSkZzY0Y0eDlyM3Ey
            RkVUdkc3RG9UY0VzRUIxOE9uZTdyNHE4TG1ZCklCZ2llS3oyWldRTmxFQkMwMmhM
            UG9NTHRLb2toY1Z3eHZ1QzNzM3NMb1kKLS0tIFlXbExOaVVRQnRJZmNXUWljZDZF
            UGp6TUNIbnF1ZVUzWm11S3A0TDRaOGsKtAaCpO2vX9vkDN8W8Zg41/6GlPsXr2si
            3aNpkNYHds0hWl58KAmqWxkcV3oKtyU6TYZV7znBch6xeo89LG2s7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-13T01:05:20Z"
    mac: ENC[AES256_GCM,data:IFiiXHS1Mr2rqdMnX5pwskECIAPEpF7khVBRYdBps/nF0TlArcDhJg7RP8zY68rNt8GKHA4zFgJp7fprqRtzjQtBBj5o/St1PBWwF6RGtDXWxgi+xBpuRWj6SQ0/KxeEABq2KrkdIZAgdLhxIORJ/1+9B8g7N9lH2ru9LsZ8TIM=,iv:azStWAwGgQQJAZ8GnbVuvyFSZiX+2KGzEmGid/czjk8=,tag:EYow79RXz1UhCv2fTFGHQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
