kind: ENC[AES256_GCM,data:lcj9zOqz,iv:a+zIQ+7w4E88J5i7nMIwsYwixvgczgKEspo71WgT9Ew=,tag:TH/GJ5HedHM3b3NaOgPnQQ==,type:str]
ansible_user: ENC[AES256_GCM,data:/DcLDOW1lA==,iv:fNnanxPCZkA+okDu8OQ7ozP3mH0OSJUw618Az1DnI2M=,tag:Mqjgfg1hYyqxVv9Vo1WBVA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:OmEIRAcUM0rF8Ibln6JHJuLFhHo=,iv:B43cQ7aRnoPgggDDwwUPpt6rDUl++J1ttFkbeuhzmF8=,tag:8NMHh6FUzcWPbl9+zejNlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk26k3ewlz9n0fs5thrpzaq2mfrkp8tx66cnlmp8jmuaqgjzksvq00h75v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJME9wdUxNMXFpM3NBeUgx
            L3FVSkZFb3FuTWJVUXE0ZkhiSEN2VDBZV2hzCk5VZUs0VWtILzlZeGUxNUsrRTMz
            eStlcU5TR0N6cGVFMEJtSis2RjBReXcKLS0tIHh3UzJVQnkvZGVxZ2J5RFl3bHgx
            MzNwbThjR2ZKRFBhMGQwdFc5T1oycEUK41O2v6vQvnagjQXakfYk54QKcaDuEHLa
            75NyW3fp72jnhej7/O8UrwUxc8xpKTLUTAgQSmSNERF8CvQ53kl0Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-13T01:05:20Z"
    mac: ENC[AES256_GCM,data:6iHhJoSAZ3gMEfN7l8UkIdRNLcOltUgNPC0iFqqoeJHE0pTpoXArwPU1i4iVzvdzGWHwimv3kTp6s7DxFA9SMU7Z/XPOlXR7qxcHwJGW4Pz6RXLJqTU0aGJbfaXmy2TmPcR+l6FQUELXzqV/rWUw/WuqGksMWESvVry1blTAFS4=,iv:aNDF471LiEToMUS/v62x2pjX9G/NOktC2PhA1/yAHnc=,tag:IyzwbwCzOFjAmW3RbYWjmw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
