apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hImvKPLEgJfpZqjYxo1HOz3GB+4w+Pi0HFQpFkLX3+Jf5ZoGac7wjQ==,iv:LpI5eQy/bYGcgQUnnTdZNX8a8XxG3jnxXD3FpTbJN9Q=,tag:ZlI7mCKwTzoI0hbE7VaW3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk26k3ewlz9n0fs5thrpzaq2mfrkp8tx66cnlmp8jmuaqgjzksvq00h75v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaDlTb2h1VFZXVUhLOEJI
            ZWZpNVE0RnY3WkFxQlNFc09ZQm03ekRJTHdFCmROb3lDWVN1MmYwOCtsL0ZicG1o
            aEJlWEUvNTJlampOZi9Nc0dIRjArbEUKLS0tIHV6aGlQaWNjWnBFbWZYSXlqR0Fz
            SElMZktsN0dLOXozbDI4cFZmL2VBWVkK4cjLBjpXGsDYedSme8Yyg1+etjmv0L+D
            MM3V+WsVO/3PZbivzUfU/9e+AdFHk8nob08oebbVHBp3pmB3jrazTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-13T01:31:39Z"
    mac: ENC[AES256_GCM,data:3gNwF1Xb0MK7Pkz9JdyCpzB7FjQykFnshC52tmwxXj/FpzGhxFTZdj0tCt0/B0Rr4VPQ0pVFyjjOM0BJJnpcfjH7Q+41R1AZ7JbLJktj+PX12sR+/qSNaRZeyjqwxapvGjpAyeH9JbP+F6qrr6N0gGT6E6yFVz+cPjvLOrsfp5o=,iv:lUcYPGzhjyKoIoVKHQq6PsdWYHooMluBv8SjgJmqXVs=,tag:9MSlyT+yXd2S8LPLi0RNrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
