apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TevHIXgSftW4c6qog8X4pab11/L7gWFlMRCCXvMiluetwlsTXW2X8g==,iv:i++m4NdS3hnrIMxyovbbWOeX/KpVWgD+h7sX97YkIo8=,tag:mFW36zEpDZA8cHVAbhT9+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk26k3ewlz9n0fs5thrpzaq2mfrkp8tx66cnlmp8jmuaqgjzksvq00h75v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYzhLZklVR2w1Zk95RjVP
            VGNXWmlveEYzQXNLeGZmL1k2NE1DdjVoSmtZCjEvdEh6Y1pac210WDQvQzc1UTlz
            amxHdDUxUDlubUpTOUxOdnoxNW9VMU0KLS0tIHQ4YkovckM1eHlNaTJkUEdEblVx
            a0lIdUlPSDE2OW1FUkQyWUI3S29tUkEKYKQt+CGJk6UJ9bE7Krwmq58up2Wm2DhQ
            HxDiXsb8UEMFmJjdJoNO+5a0Z8Dh95T2TDvYnz6gf6GL7SSARh+YEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-01T18:03:42Z"
    mac: ENC[AES256_GCM,data:caWuq/up+KaiWDlV/ecFY5tcYDQs/UGVQdG8lo2OSaWbHe/3kZlKHyPjzqBazi6nESbK56ooXwDe6trLeH2tZc4u2t1lfDnFc26wIJh1lWZr5I0C8ZG5yLVlRuRe4oJapEUu75EJ5Hh4lBzBxmdcNVxa0Fjoou0s/YvOOmeHB4w=,iv:vVYcesrhA9DVXkY4O+aQw+PrbMh9yAbuFS+4u1pqThI=,tag:/VYZewH76yIWMS5uofrT+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
