---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      defaultClass: true
      defaultFsType: xfs
      defaultClassReplicaCount: 2
    longhornUI:
      replicas: 1
    longhornConversionWebhook:
      replicas: 1
    longhornAdmissionWebhook:
      replicas: 1
    longhornRecoveryBackend:
      replicas: 1
    ingress:
      enabled: true
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: |
          10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        cert-manager.io/cluster-issuer: letsencrypt-staging
        hajimari.io/appName: longhorn
        hajimari.io/icon: game-icons:bull-horns
