apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:mDnd3CyVeKRQpnkdb8NF0elnPEnjOw//sEwDWvsGHcI4lN+QCg==,iv:Zq3Vh1cNIzYfoSAgQvkz4Pz0Oa2oKCU1X8EtHdheE+k=,tag:pO1dyp+7EHYA9PTJlJgxww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk26k3ewlz9n0fs5thrpzaq2mfrkp8tx66cnlmp8jmuaqgjzksvq00h75v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaHJxL09WYnZJQzFMTHBW
            NVovVW9ud0xURHUzb0FHeWk0N3BvMXJrL2pJCkNQSWVzd3ozK1o2N092Zk1ldjV4
            ZkxEek5HdnhlWFFiRVlTQlBLWWVGUWsKLS0tIGRCNWhLK0ZkT0U4QXdWYnpWWVVR
            N0k2TFUxRkhZT3plV1dyUWpDbFR4K1UKmlZ5GsowoRd11l/LH/vkxwRm3zbRA3QS
            QfBt/T8RSMDvnW5EVHAd+mraupBbUxcyhvxWdaE4ac38GrWxbXsL3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-13T01:31:39Z"
    mac: ENC[AES256_GCM,data:ppMKf4i9N8P1cxOnB3b3ZW/xMmAPBvXapsvU5u+fBo3yuFq8L5Yre00He2JTJf6DEUFY/GWapk+4Pv8N++WTglnS1poVF4E/N5Y56RhDQrXSdb6B5PRzNlCEd244i1zACycDeeNhk6Kd2rs0p2RxwNgs/IQWHZDzGDfpWszYdGc=,iv:fPpDya3ohiBAsy0aF2Cfrzb+Gn6JDlonk2pqnLxTPQ8=,tag:mlUjDuZUNLnLjwaK7oe/QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
