apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:8ZPoSnxO+HrOER9WsQezrSLgoZmtogA6rnJqBmwawUR9hcLyRQ==,iv:TiUP9Z+8dPXxiuNsiUHowYIrgumP43uRkw0DbmgtdtM=,tag:MsPnbcfIp7w5xKSGW92h2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk26k3ewlz9n0fs5thrpzaq2mfrkp8tx66cnlmp8jmuaqgjzksvq00h75v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ1Q0TUhPditBb0VhYkwv
            eG9MejBldXhmdHFLdnhxNWliNkZxdXpOeENjClVYMXFIa0x4MzJBdit4bFJCZjhl
            dHpxd2djbW9LNzVZYTBLTVZnSUh6cDgKLS0tIHBxc1B2eDhPM1U4RThJNThvK2Vq
            ZVBTTkFHL1dZQlRQMURNMFVMTVQwMXMK4hXAJJ3Rnw2Vu3ZsJbssyQ5FbgEbotqq
            tHqZlq8uUgkfIdfoMtvz87GLv94V8myTZPtshIuNrMcIyb20uZErrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-13T01:05:20Z"
    mac: ENC[AES256_GCM,data:PkTsgciKJCZTHK0jLyYEmACLGEwxUNIlQb1GDmqw0X35hqSiwHybQVzi4fsc3mvn/nZ6e3Bn4EmcxerDf9k2k1b7RR/nQSy2/7T6Nj5IEHW10ghniTfGxNdPFwESkrH7rSWUPsRc0exQsmURUe3f5fiHl8C1VBqIqyp97R3ckbA=,iv:Yly4UR8BpbApxOsQa6zjAAYyPUmWjFHo2WUexRdBQ4w=,tag:/Nmj0rJfTaOxriJjvWdBIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
