apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:9/n285ivO1b3CbSXAvr+83PcaFa5,iv:OfVOcCsdN3kVqU9jQ0xZgZeFq6I22wulkjGuepAB9PI=,tag:mArB5jng2L9Vrj00Lg/deg==,type:str]
    api-key: ENC[AES256_GCM,data:PKQl0CT1oCyIeYJ5kS7vX6sInC3Ro7HBtcW0KgRciY4trpjgsg==,iv:QywMXUDD5yBz6np1IRA26HiEI5vU7gADqy26PkXiBWU=,tag:LwbeSjjjm+iJG2/EwAx86w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk26k3ewlz9n0fs5thrpzaq2mfrkp8tx66cnlmp8jmuaqgjzksvq00h75v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SmxIVEU4eTE5TWFSMlpn
            dkpmMnhabE0zTUR3Y2M5NkJHRkJzSWZ0bFRnClYwVDB4QVRFMVp0M3lIano1WkdL
            RnJWQ1JGbmErcE1zWFJIVGZYVHdseUEKLS0tIDFHcWt2OTlHdlVTcVJqSWVaK0Rz
            VzdlMnhYeHJINTdTNkQ3UXJ3SmtSVXMK6vxCicjCYi7obKd6GqLsJfZSmJ94E204
            Z9JsTGTF1K3yQb/PNnKjg3PE1DdAGqm2NuWM/8649HnN93/vw4PAcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-13T01:31:39Z"
    mac: ENC[AES256_GCM,data:CPF9ETka2cJHqJjVqPJFKGZUUsqUUQN9Vcuh2tw6OdiaYOviNIWsJ/tND/9HIW5cIklu049iWuEiFBXa99eu1FHYo6e9v5lQDgUTkTH54taake1FvyqKVto43ipvzK00lbAOS7ETpxsGS64LydUHJaQg53NjmrZQ0ULjjxwAHYc=,iv:hJuAWP1K6ypV4T4HyPXBZgGPqhvOhPftaPMpn94/n/U=,tag:roHxDbsNIh3vnPKRxf/R0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
