apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:N95dYiI7fJWRjmNRH44GQSeLyDMj,iv:o/gTXhKaLqJkKAo+8bXgzyHrGCyrfgaYL5AIZydADtQ=,tag:3lcgyL8QWMg+B8BTSFMyMQ==,type:str]
    api-key: ENC[AES256_GCM,data:3G71+pCk+Q63NlhhO/agtm0PcdwMASjA43GFsmPSSq0YmbDFag==,iv:6hohjjOE2YWOfFpNobhcxW5Erj66hnrpefs+/wvfYKg=,tag:cbjqhLuBmPz17J0oPpptpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lk26k3ewlz9n0fs5thrpzaq2mfrkp8tx66cnlmp8jmuaqgjzksvq00h75v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUG1BYmFNYm5ENThoNm15
            VXI5RlBKSWk4cjMvS2ZyWUszb3pYS0dRcWxZCllNQ1dXdWdOdVI5cFhPMWxSLzc3
            bDhhNTI3cjNZTEZwbmlDVHgrKytYMFEKLS0tIG91M3FLSFBTR0RYWjV4OFVCMEQy
            TmhZUGlUcGdySjMvZjZtRmdwbUVOZ3cKh4Yr0ptxW7/39js/ASTdhK/8oi6oXq19
            UYJ1zfoEP+jI6MI/2xiIBnJNW5MXdAlJZUBH/OdGjHPgoknrQiW9ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-13T01:05:20Z"
    mac: ENC[AES256_GCM,data:q2JuHmqQxTckCdclfDEJ9AJ0C49LSLcDkbz1swBFcPTFjQd2vebCi5+Lk36XGBb9Ty76tBuayfQgOFzpHGc/XgWz8YyYU208aoPV6GHmDMxQQ3wah0xhQq8Sx8azZTRvnmDMZ/VUP3tar/E9fAB8+923qrM3TWtaIgk9VoqnQ/c=,iv:xe/nRhW/IzzTxL0LMnTSprUAd0Z3iZQ0ZWvQxedpJNM=,tag:STnCY303OfgtADex6O0njQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
