---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Asia/Jerusalem"
  KUBE_VIP_ADDR: "192.168.1.240"
  METALLB_LB_RANGE: "192.168.1.230-192.168.1.239"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.230"
  METALLB_INGRESS_ADDR: "192.168.1.231"
